### ISSUE TITLE
FAILED TO EXPORT CasC: ServiceAccountCredential is missing its descriptor

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere-sigs/ks-devops-helm-chart#22]
Got errors when I visit `http://ip:30180/configuration-as-code/viewExport`

```
        FAILED TO EXPORT
        com.cloudbees.plugins.credentials.domains.DomainCredentials#credentials: java.lang.AssertionError: class org.csanchez.jenkins.plugins.kubernetes.ServiceAccountCredential is missing its descriptor
          at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1600)
          at com.cloudbees.plugins.credentials.BaseCredentials.getDescriptor(BaseCredentials.java:76)
          at com.cloudbees.plugins.credentials.BaseCredentials.getDescriptor(BaseCredentials.java:34)
          at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$6(HeteroDescribableConfigurator.java:114)
          at io.vavr.control.Option.map(Option.java:392)
          at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:109)
          at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:55)
          at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:328)
          at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:257)
          at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:316)
          at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:328)
          at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:257)
          at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:76)
          at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:48)
          at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:328)
          at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:264)
          at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:106)
          at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:59)
```

**Comment by JohnNiang** [comment]
I think this issue has been fixed by https://github.com/jenkinsci/configuration-as-code-plugin/pull/1218.

And I have checked it manually as below:

![image](https://user-images.githubusercontent.com/16865714/147211520-6aa6f517-13e8-441f-8689-fa2452f677bc.png)

/close
